### ISSUE TITLE
Last event replayed for ProjectionActor with PersistedOffsetDb

### ISSUE THREAD

**Issue by kiequoo** [strongtyped/fun-cqrs#13]
I noticed something a bit strange when using PersistedOffsetDb.  It seems the first event has an offset of 1, second of 2 etc.  So once we have processed e.g. two events, it does saveCurrentOffset with a value of 2.  If we then shutdown the app and restart, it loads in the persisted offset, which is 2, and starts loading the stream with that offset, which causes it to process the last event with an offset of 2 again.  Not really a problem as long as the projection is idempotent put it feels slightly wrong to replay the event again when there was no error.

Not sure of the best fix, though.  Or whether it is only LevelDB that works this way (meaning LeveldbReadJournal.eventsByTag(tag, 0) and LeveldbReadJournal.eventsByTag(tag, 1) actually return exactly the same events)

**Comment by rcavalcanti** [comment]
Hmm

This seems to be a bug on the LevelDb driver. 

At work we are using our own postgres plugin (postgres + slick + play-json) and it works as expected

Note that the LeveldbReadJournal is quite experimental in akka 2.4.0

**Comment by rcavalcanti** [comment]
At least we are repeating one event and not losing one! :-)

Btw, although is not always possible, I think it's a good practice to make sure that the projections are always idempotent.

If it's not possible to stay idempotent, at least be able to skip an event.

**Comment by kiequoo** [comment]
In that case close this issue, as it's not actually causing me any issue!

**Comment by kiequoo** [comment]
> At work we are using our own postgres plugin (postgres + slick + play-json) and it works as expected

Any plans to make this public? :)

**Comment by rcavalcanti** [comment]
I think it will be made public in the near future, but I can't make any promise.

I'm not the one involved with it nor the one to decide when things get open source. 

We are working for the flemish government and the policy is to make as much as possible public as long it's not sensible. 

Which is of course the case for such a plugin.

**Comment by rcavalcanti** [comment]
It seems that there is effectively a bug here. The ProjectionActor starts the query from the currentOffset, but the currentOffset is the last processed offset.
