### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by kiequoo** [strongtyped/fun-cqrs#3]
Hi, this is pretty cool, and I just wondered if there were any plans to carry on developing it into a releasable library some time in future?

**Comment by rcavalcanti** [comment]
Hi Dan, 

Thanks for your PR. I'll have a look into it very soon. 
Really cool the idea of using the Magnet Pattern and also cool that you like the project. 

Yes, I'm planning a release but there are some corners that I want to polish before it:

1) logging is broken, I have a fake logger that prints on stdout using println. I need to fix it before releasing. I'm working on that today.
2) need more documentation and test
3) actor passivation, but I saw you were working on that as well. PR are welcome!

PS: did we met dat Amsterdam.scala? There was someone that suggested the usage of Magnet Pattern, but looking to your picture here, I don't think it was you.

**Comment by rcavalcanti** [comment]
Disregard my comment about the passivation. I just saw it is include already on PR #2.

Thanks!

**Comment by kiequoo** [comment]
Hi Renato,

Unfortunately I couldn't make it to your talk at Amsterdam.scala but one of my colleagues was there and told me about your talk and this repo.  I'm just getting started on a Akka Persistence based project myself and I ended up creating a lot of the same things in my project, so would love to scrap that part and use this lib instead :)

**Comment by rcavalcanti** [comment]
Hi @kiequoo 

I'm closing this issue as we have already a first (super experimental) release.

Feel free to add new issues and suggest features. And to send other PRs! :-)
