### ISSUE TITLE
Using a different serializer for the aggregate snapshots

### ISSUE THREAD

**Issue by kiequoo** [strongtyped/fun-cqrs#33]
When AggregateActor saves a snapshot, it saves it as a Tuple2 with the Actor state and an Aggregate Option.  However, when using an alternative serialization format (such as Json with Stamina lib), this means you need to define the serialization not for any concrete class, but for Tuple2.  This causes a problem when there is more than one aggregate as it's not possible to differentiate one from the other.

Hope this makes sense!  Do we really need to persist the state of the actor with a snapshot?  Isn't it always `Available` after processing a SnapshotOffer?

**Comment by kiequoo** [comment]
See PR... now in my .conf I can do this:

```
  actor {
    serializers {
      staminaEvents = "common.StaminaEventSerializer"
    }

    serialization-bindings {
      "chargers.Charger" = staminaEvents
      "chargers.Protocol$ChargerEvent" = staminaEvents
      "config.TariffConfig" = staminaEvents
      "config.Protocol$TariffConfigEvent" = staminaEvents
    }
  }
```
Where `chargers.Charger` and `config.TariffConfig` are my aggregates

**Comment by rcavalcanti** [comment]
You are totally right. Saving the State and the Option is useless.
