### ISSUE TITLE
Upgrade akka-stream to 2.x version

### ISSUE THREAD

**Issue by jlhervo** [strongtyped/fun-cqrs#36]
Hi,

thank you for this great library which makes CQRS/ES development really enjoyable.

I would like to know if you have any plan to upgrade akka-stream-experimental dependency to the latest version (2.0.3) ? 

The old akka-stream-experimental (1.0) is not compatible with akka-persistence journal implementations like [akka-persistence-jdbc](https://github.com/dnvriend/akka-persistence-jdbc) and throws a `NoSuchMethodError` on `ProjectionActor.recoveryCompleted`.

Note that the first "non-experimental" version will be included in Akka 2.4.2 (currently in RC) 

Regards

**Comment by rcavalcanti** [comment]
Hi @jlhervo, 

I wasn't aware of it. Thanks for the heads up.

I think I should monitor it closer. Things are expected to get broken very easy with experimental modules.

Have you tried to update it yourself? Is it just matter of updating the dependency? 

Anyway, I can do it. But I won't be able to do it before Tuesday. If you want you can send me a PR. 

Thanks

**Comment by jlhervo** [comment]
Hi,

as Akka 2.4.2 will be released soon (with first non-experimental akka-stream version), we can expect that future versions will not break official TCK.

The only breaking change I found was `EventsSourceProvider` not returning `Unit` but `akka.NotUsed` as materialized value.

I created PR #37 (based on the forked version I use in my projects). All tests passed but let me know if something seems broken.

**Comment by rcavalcanti** [comment]
Hi, 

Just merged your PR. Thanks a lot. 

I see that you are using a fork from the develop branch. I'm currently incorporating some feedback I got during DDD Europe conference and it'll probably break your project.

It's not a big bang, but the Binding DSL will change a bit and the AggregateService will be replaced by a AggregateRef (much like a ActorRef). 

The Lottery sample will be updated accordingly, so you see how to migrate.

Cheers,
