### ISSUE TITLE
Eventhandling idempotency possibly flawed

### ISSUE THREAD

**Issue by pjan** [strongtyped/fun-cqrs#65]
I believe that [this merge](https://github.com/strongtyped/fun-cqrs/commit/bb359ddc23bc9cc4ce8852594cc7e3f5ef5038b2), which tries to make sure events don't get applied to the state more than once, is partly flawed.

Indeed, the in-memory state will be the correct one, but as far as I can tell, events still get persisted to the persistent backend, and upon replay, will be used to calculate the new state.

In order to avoid this, you need to make sure that your internal `Success` message is idempotent, which can e.g. be done if you add a version (which could be the total event counter) to your `AggregateLike` and compare that version number before persisting the events.

**Comment by rcavalcanti** [comment]
I don't get your point. 

Events are applied after persisting and internal state is only update after that. 

Replay only happens when aggregate is re-instantiated in which case they are not applied twice because whether we come from 0 or from a snapshot. There is no replay happening on a previous state that stays in-memory.

**Comment by pjan** [comment]
Please correct me if I'm wrong, but this is how I understand it:

1. `AggregateActor` receives a `Command`
2. The `applyCommand` of the `behaviour`/`interpreter` gets called. This executes asynchronously (future)
3. Upon success of the future, you have both the resulting `events` and updated `AggregateState`, which you send to yourself in a `Successful`
4. You receive the `Successful`, persist the events, and update your state to that updated `AggregateState` upon a successful persist

Now you want to protect against the events being applied multiple times (not the same as protecting against the same events happening because you received the command twice). This can only happen (very unlikely though) if the `Successful` you send in 3. arrives twice in 4.

What happens in your code is, you save the events first, and keep the state of that `Successful` message. If this message happens 2 times, the state will indeed be correct (events only applied once). However, your events are persisted twice. If you now replay the events when "waking up" the `Aggregate`, the events will be applied twice to the state.

If you want to avoid this, you have to make sure the events aren't persisted either, and have idempotent semantics in your `Successful`.

**Comment by rcavalcanti** [comment]
But under which circumstances can the `Successful` message arrive twice in 4?

**Comment by pjan** [comment]
This is impossible, but I understood this was what you were trying to protect against. Most likely my mistake, and misread / misunderstood. Can close. Apologies.

**Comment by rcavalcanti** [comment]
My intention was to prevent other commands to be processed while we are still persisting the events. Classical become/unbecome thing.

I'm closing this one.
