### ISSUE TITLE
Improve error message when Aggregate is not configured

### ISSUE THREAD

**Issue by rabzu** [strongtyped/fun-cqrs#69]
Currently the error message is:

`java.util.NoSuchElementException: null
[info]  at scala.collection.concurrent.TrieMap.apply(TrieMap.scala:837) ~[scala-library-2.11.8.jar:na]
[info]  at io.funcqrs.akka.backend.AkkaBackend$class.aggregateRef(AkkaBackend.scala:32) ~[fun-cqrs-akka_2.11-0.4.6.jar:0.4.6]`

**Comment by rcavalcanti** [comment]
fixed on 0.4.11
