### ISSUE TITLE
Actor is not unique exception when configuring two backends in the same actor system. 

### ISSUE THREAD

**Issue by aiacovella** [strongtyped/fun-cqrs#74]
When I create two back ends in the same actor system as shown [here](https://gist.github.com/aiacovella/a315cd49fa9aa3e02bb0d469692769c0)

I get the following [exception](https://gist.github.com/aiacovella/be4252d43e745cb048ed2689321dbaef)

**Comment by aiacovella** [comment]
This happens when you have two anonymous actors defined. For now I got around it by making them classes.  The problem seems to be [here](https://github.com/strongtyped/fun-cqrs/blob/develop/modules/akka/src/main/scala/io/funcqrs/akka/backend/AkkaBackend.scala#L24) because the two anonymous actors will return the same name.

**Comment by rcavalcanti** [comment]
fixed by PR #78
